spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/farmaciadb
    username: postgres
    password: 2424

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always

server:
  port: 8080
#  port: 7666

# swagger-path
springdoc:
  swagger-ui:
    path: /docs.html

#  servlet:
#    context-path=/DEVinPharmacy: