spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/farmaciadb
    username: postgres
    password: 2424

  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always

  jackson:
    default-property-inclusion: NON_NULL

server:
  port: 8080
#  port: 7666

# swagger-path
springdoc:
  swagger-ui:
    path: /docs.html

#  servlet:
#    context-path: /api/v1: